### PR TITLE
Group20

### PR DESCRIPTION
**Pull request by hyy7**
Community Contribution Group 20
We didn't change anything in Graphics_Community.Rproj, but once we pulled it we don't know how to delete it. Sorry about that.

### CODE REVIEW

**Comment by jtr13** [comment]
No problem.  Please though add a link in the index.md file (see instructions) and then commit again.

**Comment by hyy7** [comment]
Thanks professor. Do you think it is also necessary for us to upload our
dataset file? I think that will be helpful if others what to try it on
their own computer.

Joyce Robbins <notifications@github.com> 于 2019年3月29日周五 09:45写道：

**Comment by jtr13** [comment]
Yes, it would be useful to do so. You can create a data folder and put it in there, and add a link either to the index.md file or to your actual project explaining where one can find  the data.  I'm going to merge this one as is, so you should add the data on a new branch and create a new pull request. (Good practice!)

**Comment by jtr13** [comment]
🎉

**Comment by jtr13** [comment]
Also, I deleted your .Rproj file.  You should put that in .gitignore since it's specific to your local setup.

**Pull request merged**
